extends Node2D

# Autogenerated stub for `Bat` enemy. Replace with real logic.
# TODO: Implement movement, damage, and signals.

@export var health: int = 10
@export var speed: float = 100.0

func _ready() -> void:
    pass

func _process(delta: float) -> void:
    pass
