extends Node

# Autogenerated stub for `ProjectilePool` system. Replace with real pooling logic.

var pool := []

func _ready() -> void:
    pass

func get_projectile() -> Node:
    # Return a projectile instance from the pool (stub)
    return null
